unique_ids:
  assets:
    standard-page.html: PTASTCLLDNDYQVORUMARXNWZAZMBN4UQ
    theme.css: DJATZQP7LUJIYEAS6ZLRZFAPTPGPC3CA
  forms:
    Form1: WRW5SL72EJ7P5FTC3FBPTGM5HLE3B3SV
  modules: {}
  scripts: {}
  server_modules: {}
